baseURL = 'https://markbeachill.github.io/site-learn/'
languageCode = 'en-us'
title = 'Chequered History Learning'
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowToc = true
  ShowBreadCrumbs = true
